# -*- coding: utf-8 -*-
"""PAA - Força Bruta - Problema da Mochila.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1662skbRcaEOBX3hYIjCbys_xnbNOeBZC
"""

def mochila_fracionaria(c, n, p, v):
  x = [0.0 for i in range(n)]
  
  for j in range(n-1, 0, -1):
    if (p[j] <= c):
      x[j] = 1.0
      c -= p[j]
    
    else:
      x[j] = round(c / float(p[j]), 2)  # frequência (com 2 casas decimais)
      c = 0
      
  return x
  

# exemplo
c = 50
n = 5
p = [10, 20, 20, 30, 40]
v = [100, 300, 400, 600, 840]
x = mochila_fracionaria(c, n, p, v)

print("p: " + str(p))
print("v: " + str(v))
print("x: " + str(x))